# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('can_act', models.BooleanField()),
                ('max_invites', models.IntegerField()),
                ('needs_moderation', models.BooleanField()),
                ('is_moderator', models.BooleanField()),
                ('can_bless', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='exchanger.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invite',
            name='emitent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='exchanger.User'),
        ),
        migrations.AddField(
            model_name='invite',
            name='newbie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='exchanger.User'),
        ),
    ]
