# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import exchanger.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=2048)),
                ('ref_type', models.IntegerField(choices=[(0, 'Code'), (1, 'Link')])),
                ('value_re', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='exchanger.User')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='exchanger.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=2048)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=exchanger.models.Provider._get_picture_path)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
